# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayWoowManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'lottie-ios'
pod 'SDWebImageSwiftUI'
pod 'CreditCardReader/SwiftUI'
pod 'Mantis', '~> 1.9.0'

  # Pods for Manager
  # Pods for PayWoowManager

end
