# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayWoow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'CreditCardReader/SwiftUI'
pod 'lottie-ios'
pod 'NSFWDetector'
pod 'techsigncloudlibs', '1.7.8-wrapper', :source => 'https://github.com/Techsign/PODSPECS.git'
  # Pods for PayWoow

end
